{ ... }:
{
  imports =
    [ (import ./invidious.nix) ]
    ++ [ (import ./anubis.nix) ]
    ++ [ (import ./borg.nix) ]
    ++ [ (import ./binternet-proxy.nix) ]
    ++ [ (import ./bluemap-proxy.nix) ]
    ++ [ (import ./docker.nix) ]
    # ++ [ (import ./frp.nix) ]
    ++ [ (import ./forgejo.nix) ]
    ++ [ (import ./grafana.nix) ]
    ++ [ (import ./guacamole.nix) ]
    ++ [ (import ./gokapi.nix) ]
    ++ [ (import ./jellyfin.nix) ]
    ++ [ (import ./librey-proxy.nix) ]
    ++ [ (import ./lidarr.nix) ]
    ++ [ (import ./matrix/default.nix) ]
    ++ [ (import ./mumble.nix) ]
    ++ [ (import ./monitoring.nix) ]
    ++ [ (import ./ntfy.nix) ]
    ++ [ (import ./nginx.nix) ]
    ++ [ (import ./radicale.nix) ]
    ++ [ (import ./readarr.nix) ]
    ++ [ (import ./sharkey-proxy.nix) ]
    # ++ [(import ./komga.nix)]
    # ++ [ (import ./prosody.nix) ]
    ++ [ (import ./tailscale.nix) ]
    # ++ [(import ./smart-monitoring.nix)]
    ++ [(import ./jitsi-meet.nix)]:
}
