{ ... }:
{
  imports =
    [ (import ./invidious.nix) ]
    ++ [ (import ./anubis.nix) ]
    ++ [ (import ./borg.nix) ]
    ++ [ (import ./binternet-proxy.nix) ]
    ++ [ (import ./bluemap-proxy.nix) ]
    ++ [ (import ./docker.nix) ]
    ++ [ (import ./email.nix) ]
    ++ [ (import ./forgejo.nix) ]
    ++ [ (import ./grafana.nix) ]
    ++ [ (import ./guacamole.nix) ]
    ++ [ (import ./gokapi.nix) ]
    ++ [ (import ./jellyfin.nix) ]
    ++ [ (import ./librey-proxy.nix) ]
    ++ [ (import ./lidarr.nix) ]
    ++ [ (import ./matrix/default.nix) ]
    ++ [ (import ./mumble.nix) ]
    ++ [ (import ./monitoring.nix) ]
    # ++ [ (import ./minio.nix) ]
    # ++ [ (import ./nextcloud.nix) ]
    ++ [ (import ./ntfy.nix) ]
    ++ [ (import ./nginx.nix) ]
    ++ [ (import ./nix-serve.nix) ]
    ++ [ (import ./ollama.nix) ]
    ++ [ (import ./paperless-ngx.nix) ]
    ++ [ (import ./radicale.nix) ]
    ++ [ (import ./remote-build.nix) ]
    ++ [ (import ./readarr.nix) ]
    ++ [ (import ./sharkey-proxy.nix) ]
    # ++ [ (import ./komga.nix) ]
    # ++ [ (import ./xmpp.nix) ]
    ++ [ (import ./tailscale.nix) ]
    ++ [ (import ./vaultwarden.nix) ];
  # ++ [ (import ./smart-monitoring.nix) ]
  # ++ [ (import ./jitsi-meet.nix) ]
}
