# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware = {
    asahi = {
      enable = true;
      avd.enable = true;
      avd.vaapi-support = true;
      setupAsahiSound = true;
      peripheralFirmwareDirectory = ./firmware;
    };
  };

  boot = {
    kernelParams = [
      "appledrm.show_notch=1"
      "hid_apple.swap_fn_leftctrl=1"
      "hid_apple.swap_opt_cmd=1"
    ];
    initrd.systemd.enable = true; # required by lz4 in zram
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = false;
    };
    kernel.sysctl."vm.mmap_rnd_bits" = 18;
  };

  boot.initrd.availableKernelModules = [
    "usb_storage"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  boot.initrd.luks.devices."crypt".device = "/dev/disk/by-uuid/e482f2ab-7be3-48be-bb49-cc2661dd5eb6";

  fileSystems."/home" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F9B2-1EF8";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  #fileSystems."/boot" =
  #  { device = "/boot";
  #    fsType = "none";
  #    options = [ "bind" ];
  #  };

  swapDevices = [
    {
      device = "/dev/nvme0n1p6";
      randomEncryption.enable = true;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
