# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  powerManagement = {
    enable = true;
    powertop.enable = true;
    cpuFreqGovernor = lib.mkDefault "ondemand";
  };

  boot = {
    kernelParams = [
      "mem_sleep_default=deep"
    ];
    kernelModules = [
      "acpi_call"
      "kvm-intel "
    ];
    kernelPackages = pkgs.linuxPackages_latest;
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      systemd-boot.configurationLimit = 10;
    };
    extraModulePackages = with config.boot.kernelPackages; [
      acpi_call
    ];
  };

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];

  boot.initrd.luks.devices."luks-c4154cca-9246-40e7-9f92-f67cf412f718".device =
    "/dev/disk/by-uuid/c4154cca-9246-40e7-9f92-f67cf412f718";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/28283b70-d1ab-4c1e-9e9e-4efdcb051553";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-577b813a-bbe2-479c-b439-b91964e9b36c".device =
    "/dev/disk/by-uuid/577b813a-bbe2-479c-b439-b91964e9b36c";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/44F1-737B";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/41da47c8-b3ba-4773-941e-a35dfd73aaef"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
